source :rubygems
gem 'sinatra'
gem 'sass'
gem 'coffee-script'
gem 'closure-compiler'
gem 'shotgun'
gem 'rake'
gem 'jasmine'
gem 'jasmine-headless-webkit'
gem 'rspec'
gem 'debugger'
gem 'require_all'
# gem 'keystone', :git => 'git@bitbucket.org:musicone/keystone.git'
gem 'keystone', :path => '~/development/spikes/keystone'